[package]
name = "mind-map-rust"
version = "0.1.0"
edition = "2021"

[dependencies]

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eframe = "0.28.1"
egui = "0.28.1"
egui_glium = "0.26.3"   
chrono = "0.4"
